debug: true
logging:
  level: info
server:
  context-path: /
  port: 1111
  address: 127.0.0.1

## 增加配置监控
management:
  security:
    enabled: false
eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: false
    fetch-registry: false
    service-url: http://${eureka.instance.hostname}:${server.port}/eureka/
