logging:
  level: info
server:
  context-path: /
  port: 9090
spring:
  data:
    mongodb:
      host: 192.168.229.148
      username: gamble
      password: gamblepwd
      database: gamble
      port: 30000
  redis:
    host: 127.0.0.1
    port: 6379
    database: 0
    password:
    pool:
      max-active: 8
      max-wait: 1
      max-idle: 8
      min-idle: 0
    timeout: 200
