debug: true
logging:
  level: info
server:
  port: 9090
  servlet:
    context-path: /
spring:
  activemq:
    broker-url: tcp://127.0.0.1:61616
    user: admin
    password: admin
    pool:
      enabled: false
