debug: true

logging:
  level: info

server:
  context-path: /
  port: 9090

#spring:
#  data:
#    elasticsearch:
#      cluster-name: name1
#      cluster-nodes: node1
#      repositories:
#        enabled: false
