debug: true

logging:
  level: info

server:
  port: 9090
  servlet:
    context-path: /

#spring:
#  data:
#    elasticsearch:
#      cluster-name: name1
#      cluster-nodes: node1
#      repositories:
#        enabled: false
